/*
 * Copyright 2026 Endeavour Predict CIC.
 *
 *
 * This file is part of QFracture-2016 (http://qfracture.org).
 *
 * QFracture-2016 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * QFracture-2016 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with QFracture-2016.  If not, see <a href="http://www.gnu.org/licenses">http://www.gnu.org/licenses</a>.
 *
 * Additional terms
 *
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at https://github.com/endeavour-predict/EP-Open-source, which faithfully implements QRISK3-2017.
      *   Endeavour Predict CIC Have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
      *   Changes to the code may be made since the original release, and Endeavour Predict CIC cannot guarantee that the code you are using is a faithful implementation of QFracture-2016.
      *   It is the responsibility of the manufacturer of your device to ensure that the code you are using is a faithful implementation of QFracture-2016, and that it produces the same
      *   results as the original code found at https://github.com/endeavour-predict/EP-Open-source,
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 *
 * End of additional terms
 *
 */

static double fracture4_male_raw(
int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_carehome,int b_corticosteroids,int b_cvd,int b_dementia,int b_epilepsy2,int b_falls,int b_liver,int b_malabsorption,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int fh_osteoporosis,int smoke_cat,int surv
)
{
	double survivor[11] = {
		0,
		0.999435424804688,
		0.998826444149017,
		0.998191893100739,
		0.997505903244019,
		0.996722519397736,
		0.995886385440826,
		0.994963765144348,
		0.993958413600922,
		0.992862939834595,
		0.991695225238800
	};

	/* The conditional arrays */

	double Ialcohol[6] = {
		0,
		-0.1129648713412066400000000,
		-0.1019933147383609900000000,
		-0.0087172177838055233000000,
		0.2378367291894386800000000,
		0.5900674828324269400000000
	};
	double Iethrisk[10] = {
		0,
		0,
		-0.2497759361694920600000000,
		-0.3388723409363771900000000,
		-1.1780652312756217000000000,
		-0.5637536128417445200000000,
		-0.8802674221403056200000000,
		-0.6220839068056021000000000,
		-0.8700240760084387800000000,
		-0.3586934603990843400000000
	};
	double Ismoke[5] = {
		0,
		0.0374622547112923930000000,
		0.2536654624283247200000000,
		0.2728541689904917000000000,
		0.3498259780437700300000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_2 = dage;
	double age_1 = pow(dage,0.5);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_2 = pow(dbmi,-0.5);
	double bmi_1 = pow(dbmi,-1);

	/* Centring the continuous variables */

	age_1 = age_1 - 2.201908826828003;
	age_2 = age_2 - 4.848402023315430;
	bmi_1 = bmi_1 - 0.375702142715454;
	bmi_2 = bmi_2 - 0.612945437431335;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Ialcohol[alcohol_cat6];
	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * -8.5962113395742179000000000;
	a += age_2 * 2.3534585567599957000000000;
	a += bmi_1 * 18.3534753639015770000000000;
	a += bmi_2 * -19.0905273467733320000000000;

	/* Sum from boolean values */

	a += b_antidepressant * 0.4185009802564456600000000;
	a += b_anycancer * 0.2923849667849617900000000;
	a += b_asthmacopd * 0.2658243150152003200000000;
	a += b_carehome * 0.0946727309614458920000000;
	a += b_corticosteroids * 0.2601592893954755000000000;
	a += b_cvd * 0.2155420976820900700000000;
	a += b_dementia * 0.6253066390475994200000000;
	a += b_epilepsy2 * 0.6695708064301426600000000;
	a += b_falls * 0.4477141342626502200000000;
	a += b_liver * 0.7970936081024936300000000;
	a += b_malabsorption * 0.2508921035498924400000000;
	a += b_parkinsons * 0.8254276340218873500000000;
	a += b_ra_sle * 0.3846585832735093200000000;
	a += b_renal * 0.4479672880062486300000000;
	a += b_type1 * 1.0121689145067305000000000;
	a += b_type2 * 0.2439254432490279300000000;
	a += fh_osteoporosis * 0.9898717512466593800000000;

	/* Sum from interaction terms */


	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}
