/*
 * Copyright 2026 Endeavour Predict CIC.
 *
 *
 * This file is part of QFracture-2016 (http://qfracture.org, http://svn.clinrisk.co.uk/qfracture).
 *
 * QFracture-2016 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * QFracture-2016 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with QFracture-2016.  If not, see <a href="http://www.gnu.org/licenses">http://www.gnu.org/licenses</a>.
 *
 * Additional terms
 *
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at https://github.com/endeavour-predict/EP-Open-source, which faithfully implements QRISK3-2017.
      *   Endeavour Predict CIC Have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
      *   Changes to the code may be made since the original release, and Endeavour Predict CIC cannot guarantee that the code you are using is a faithful implementation of QFracture-2016.
      *   It is the responsibility of the manufacturer of your device to ensure that the code you are using is a faithful implementation of QFracture-2016, and that it produces the same
      *   results as the original code found at https://github.com/endeavour-predict/EP-Open-source,
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 *
 * End of additional terms
 *
 */

static double nof_male_raw(
int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_carehome,int b_corticosteroids,int b_cvd,int b_dementia,int b_epilepsy2,int b_falls,int b_fracture4,int b_liver,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int fh_osteoporosis,int smoke_cat,int surv
)
{
	double survivor[11] = {
		0,
		0.999893844127655,
		0.999774158000946,
		0.999640882015228,
		0.999497473239899,
		0.999327778816223,
		0.999136328697205,
		0.998924136161804,
		0.998683452606201,
		0.998405933380127,
		0.998105704784393
	};

	/* The conditional arrays */

	double Ialcohol[6] = {
		0,
		-0.1989277879915676800000000,
		-0.2613512785873652300000000,
		-0.2165261229261542800000000,
		0.0771682474573718860000000,
		0.4865889592245968300000000
	};
	double Iethrisk[10] = {
		0,
		0,
		-0.5197707213726646700000000,
		-0.4273622890290790200000000,
		-1.3616785101903839000000000,
		-0.8979303273750973700000000,
		-0.9201178622676105000000000,
		-0.5850249719802090900000000,
		-1.2625832440588742000000000,
		-0.3934722541162818400000000
	};
	double Ismoke[5] = {
		0,
		0.0172107719322296650000000,
		0.4334014580484051300000000,
		0.4706305455101631500000000,
		0.6359078620828390000000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = pow(dage,3);
	double age_2 = pow(dage,3)*log(dage);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = pow(dbmi,-2);

	/* Centring the continuous variables */

	age_1 = age_1 - 113.993118286132810;
	age_2 = age_2 - 179.962387084960940;
	bmi_1 = bmi_1 - 0.141164988279343;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Ialcohol[alcohol_cat6];
	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * 0.0419825595398811420000000;
	a += age_2 * -0.0152519952339723320000000;
	a += bmi_1 * 5.7167542710069563000000000;

	/* Sum from boolean values */

	a += b_antidepressant * 0.4267786880099018700000000;
	a += b_anycancer * 0.2328499751645417800000000;
	a += b_asthmacopd * 0.2348015554978777900000000;
	a += b_carehome * 0.1879003102725514400000000;
	a += b_corticosteroids * 0.1740108568014504500000000;
	a += b_cvd * 0.2376902595200354700000000;
	a += b_dementia * 0.8464083378165536700000000;
	a += b_epilepsy2 * 0.7023595003140320500000000;
	a += b_falls * 0.3461048734913962900000000;
	a += b_fracture4 * 0.6405104279877627000000000;
	a += b_liver * 0.8355037910863250000000000;
	a += b_parkinsons * 0.9880686646887743000000000;
	a += b_ra_sle * 0.4201341417376428000000000;
	a += b_renal * 0.5718927887809727200000000;
	a += b_type1 * 1.3669282519025776000000000;
	a += b_type2 * 0.3057043662392859300000000;
	a += fh_osteoporosis * 0.2733760510310951400000000;

	/* Sum from interaction terms */


	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}
