/*
 * Copyright 2026 Endeavour Predict CIC.
 *
 *
 * This file is part of QFracture-2016 (http://qfracture.org).
 *
 * QFracture-2016 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * QFracture-2016 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with QFracture-2016.  If not, see <a href="http://www.gnu.org/licenses">http://www.gnu.org/licenses</a>.
 *
 * Additional terms
 *
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at https://github.com/endeavour-predict/EP-Open-source, which faithfully implements QRISK3-2017.
      *   Endeavour Predict CIC Have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
      *   Changes to the code may be made since the original release, and Endeavour Predict CIC cannot guarantee that the code you are using is a faithful implementation of QFracture-2016.
      *   It is the responsibility of the manufacturer of your device to ensure that the code you are using is a faithful implementation of QFracture-2016, and that it produces the same
      *   results as the original code found at https://github.com/endeavour-predict/EP-Open-source,
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 *
 * End of additional terms
 *
 */

static double fracture4_female_raw(
int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_corticosteroids,int b_cvd,int b_dementia,int b_endocrine,int b_epilepsy2,int b_falls,int b_hrt_oest,int b_liver,int b_malabsorption,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int fh_osteoporosis,int smoke_cat,int surv
)
{
	double survivor[11] = {
		0,
		0.998549282550812,
		0.996993362903595,
		0.995339095592499,
		0.993514478206635,
		0.991504669189453,
		0.989245474338531,
		0.986799359321594,
		0.984268248081207,
		0.981499433517456,
		0.978452086448669
	};

	/* The conditional arrays */

	double Ialcohol[6] = {
		0,
		-0.0161196598427115580000000,
		0.0181421919546882990000000,
		0.0870398130913111050000000,
		0.4850876681648371200000000,
		0.4521470045723863200000000
	};
	double Iethrisk[10] = {
		0,
		0,
		-0.4256606921636625400000000,
		-0.5543209119502141600000000,
		-0.9182601097806930600000000,
		-0.6819360653148304200000000,
		-1.4668483404988077000000000,
		-0.9101238114228446000000000,
		-0.6421783317544739200000000,
		-0.5036829432634510900000000
	};
	double Ismoke[5] = {
		0,
		0.0557356934305611660000000,
		0.1633895661701352800000000,
		0.1540488338696587000000000,
		0.2329771591757904500000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = pow(dage,2);
	double age_2 = pow(dage,3);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = pow(dbmi,-1);

	/* Centring the continuous variables */

	age_1 = age_1 - 25.463895797729492;
	age_2 = age_2 - 128.495315551757810;
	bmi_1 = bmi_1 - 0.382189363241196;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Ialcohol[alcohol_cat6];
	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * 0.1488230617216508300000000;
	a += age_2 * -0.0095516624764288762000000;
	a += bmi_1 * 2.8180291389827810000000000;

	/* Sum from boolean values */

	a += b_antidepressant * 0.2935891578881283900000000;
	a += b_anycancer * 0.1175522733147793100000000;
	a += b_asthmacopd * 0.1997193753352899900000000;
	a += b_corticosteroids * 0.2187020094246774900000000;
	a += b_cvd * 0.1419643725503051700000000;
	a += b_dementia * 0.4697387263085152100000000;
	a += b_endocrine * 0.1105394028217592300000000;
	a += b_epilepsy2 * 0.4024460098604033000000000;
	a += b_falls * 0.3322321626303583700000000;
	a += b_hrt_oest * -0.2027864456358232400000000;
	a += b_liver * 0.4831161576961586200000000;
	a += b_malabsorption * 0.1687477801835574600000000;
	a += b_parkinsons * 0.4742239358039181400000000;
	a += b_ra_sle * 0.2267059327471904200000000;
	a += b_renal * 0.2508648723794006400000000;
	a += b_type1 * 0.7832887160932293600000000;
	a += b_type2 * 0.2363869657814060800000000;
	a += fh_osteoporosis * 0.3837949755860494700000000;

	/* Sum from interaction terms */


	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}
