/*
 * Copyright 2026 Endeavour Predict CIC.
 *
 *
 * This file is part of QFracture-2016 (http://qfracture.org).
 *
 * QFracture-2016 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * QFracture-2016 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with QFracture-2016.  If not, see <a href="http://www.gnu.org/licenses">http://www.gnu.org/licenses</a>.
 *
 * Additional terms
 *
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at https://github.com/endeavour-predict/EP-Open-source, which faithfully implements QRISK3-2017.
      *   Endeavour Predict CIC Have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
      *   Changes to the code may be made since the original release, and Endeavour Predict CIC cannot guarantee that the code you are using is a faithful implementation of QFracture-2016.
      *   It is the responsibility of the manufacturer of your device to ensure that the code you are using is a faithful implementation of QFracture-2016, and that it produces the same
      *   results as the original code found at https://github.com/endeavour-predict/EP-Open-source,
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 *
 * End of additional terms
 *
 */
static double nof_female_raw(
int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_corticosteroids,int b_cvd,int b_dementia,int b_endocrine,int b_epilepsy2,int b_falls,int b_fracture4,int b_hrt_oest,int b_liver,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int smoke_cat,int surv
)
{
	double survivor[11] = {
		0,
		0.999798893928528,
		0.999581158161163,
		0.999346554279327,
		0.999083101749420,
		0.998790085315704,
		0.998455047607422,
		0.998097419738770,
		0.997704565525055,
		0.997259438037872,
		0.996739983558655
	};

	/* The conditional arrays */

	double Ialcohol[6] = {
		0,
		-0.1261758201330289700000000,
		-0.1373243347908413300000000,
		-0.1133616834893930700000000,
		0.4017887033571813100000000,
		0.5006572131880983000000000
	};
	double Iethrisk[10] = {
		0,
		0,
		-0.5210282168631360500000000,
		-0.4177942104837170100000000,
		-0.7951236994041091000000000,
		-0.6588104797725504700000000,
		-1.5796225547799494000000000,
		-1.0777580735638324000000000,
		-0.8521785631761629200000000,
		-0.5715035184075031300000000
	};
	double Ismoke[5] = {
		0,
		0.0294188680292629120000000,
		0.3263756428320784300000000,
		0.3496437278702089800000000,
		0.5155176914691816900000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = pow(dage,2);
	double age_2 = pow(dage,3);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = pow(dbmi,-2);

	/* Centring the continuous variables */

	age_1 = age_1 - 25.815217971801758;
	age_2 = age_2 - 131.163711547851560;
	bmi_1 = bmi_1 - 0.146003782749176;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Ialcohol[alcohol_cat6];
	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * 0.2600550792365882700000000;
	a += age_2 * -0.0171243805014380560000000;
	a += bmi_1 * 5.2078461133313851000000000;

	/* Sum from boolean values */

	a += b_antidepressant * 0.2961370228136101500000000;
	a += b_anycancer * 0.1141350453612936500000000;
	a += b_asthmacopd * 0.1458646814083802100000000;
	a += b_corticosteroids * 0.1780165520696634900000000;
	a += b_cvd * 0.1386725900431314300000000;
	a += b_dementia * 0.5593392615149843600000000;
	a += b_endocrine * 0.1988932345923676800000000;
	a += b_epilepsy2 * 0.4544705186649458100000000;
	a += b_falls * 0.2682716649575493400000000;
	a += b_fracture4 * 0.4485906129569035000000000;
	a += b_hrt_oest * -0.2585315313281359400000000;
	a += b_liver * 0.4764394125573222500000000;
	a += b_parkinsons * 0.5444815361802923800000000;
	a += b_ra_sle * 0.3084108024586954500000000;
	a += b_renal * 0.2487817440674148200000000;
	a += b_type1 * 1.3350155588126134000000000;
	a += b_type2 * 0.4128514481325198400000000;

	/* Sum from interaction terms */


	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}
